### ISSUE TITLE
“npm run pack-win” 打包未成功

### ISSUE THREAD

**Issue by JackChius** [ConardLi/electron-react#2]
【暂无影响】 
`asar using is disabled — it is strongly not recommended solution`
据说要保留asar压缩打包体积的模式，在package.json的build配置项下，将asar，设置为true后没此提示

【Error】接下来出现了红字报错信息

大致意思可能是设置不了ICON
 **packaging       platform=win32 arch=ia32 electron=2.0.4 appOutDir=dist\win-ia32-unpacked
Error: Exit code: 1. Command failed: C:\Users\hiu\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.4.0\rcedit-ia32.exe D:\mydev\electron-react\dist\win-ia32-unpacked\electron-react.exe --set-version-string FileDescription electron-react --set-version-string ProductName electron-react --set-version-string LegalCopyright Copyright © 2019 shiqi.li --set-file-version 1.1.7 --set-product-version 1.1.7.0 --set-version-string InternalName electron-react --set-version-string OriginalFilename  --set-version-string CompanyName shiqi.li --set-icon D:\mydev\electron-react\icon.ico
Reserved header is not 0 or image type is not icon for 'D'
Fatal error: Unable to set icon**

```
Error: Exit code: 1. Command failed: C:\Users\hiu\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.4.0\rcedit-ia32.exe D:\mydev\electron-react\dist\win-ia32-unpacked\electron-react.exe --set-version-string FileDescription electron-react --set-version-string ProductName electron-react --set-version-string LegalCopyright Copyright © 2019 shiqi.li --set-file-version
1.1.7 --set-product-version 1.1.7.0 --set-version-string InternalName electron-react --set-version-string OriginalFilename  --set-version-string CompanyName shiqi.li --set-icon D:\mydev\electron-react\icon.ico
Reserved header is not 0 or image type is not icon for 'D'
Fatal error: Unable to set icon

Reserved header is not 0 or image type is not icon for 'D'
Fatal error: Unable to set icon

    at D:\mydev\electron-react\node_modules\builder-util\src\util.ts:126:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.signAndEditResources (D:\mydev\electron-react\node_modules\app-builder-lib\src\winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (D:\mydev\electron-react\node_modules\app-builder-lib\src\winPackager.ts:363:21)
    at go$readdir$cb (D:\mydev\electron-react\node_modules\graceful-fs\graceful-fs.js:162:14)
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at D:\mydev\electron-react\node_modules\app-builder-lib\src\winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (D:\mydev\electron-react\node_modules\app-builder-lib\src\winPackager.ts:355:73)
    at D:\mydev\electron-react\node_modules\app-builder-lib\src\platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (D:\mydev\electron-react\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at D:\mydev\electron-react\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (D:\mydev\electron-react\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at D:\mydev\electron-react\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (D:\mydev\electron-react\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at D:\mydev\electron-react\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (D:\mydev\electron-react\node_modules\app-builder-lib\src\packager.ts:396:24)
    at D:\mydev\electron-react\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at D:\mydev\electron-react\node_modules\graceful-fs\graceful-fs.js:111:16
    at D:\mydev\electron-react\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (D:\mydev\electron-react\node_modules\app-builder-lib\src\packager.ts:335:133)
    at D:\mydev\electron-react\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (D:\mydev\electron-react\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (D:\mydev\electron-react\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (D:\mydev\electron-react\node_modules\electron-builder\src\builder.ts:228:10)
    at then (D:\mydev\electron-react\node_modules\electron-builder\src\cli\cli.ts:49:19)
```

**Comment by JackChius** [comment]
**补充**
electron 版本为 2.0.4
win10 
node => v10.15.2
npm => 6.4.1

**Comment by LiFBoy** [comment]
同样碰到这个问题，怎么结局呢

**Comment by LiFBoy** [comment]
同样碰到这个问题，怎么解决呢

**Comment by shixw** [comment]
根目录下的 icon.ico 图表有问题 我换了一个就可以打包成功了 但是安装完打开还是有问题
